name: helm-release

on:
  push:
    branches:
      - main

jobs:
  call-update-helm-repo:
    uses: grafana/helm-charts/.github/workflows/update-helm-repo.yaml@krajo/20220526-reuseworkflows
    with:
      cr_configfile: operations/helm/cr.yaml
      charts_dir: operations/helm/charts
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      # See https://github.com/grafana/helm-charts/blob/main/INTERNAL.md about this key
      gpg_key_base64: ${{ secrets.HELM_SIGN_KEY_BASE64 }}
